---

port: 4000
host: 0.0.0.0
safe: false


### site serving configuration ###
exclude: [CNAME, README.md, .gitignore]
permalink: /:title ## disables post output
timezone: null
lsi: false
markdown: kramdown


### content configuration ###
title:       "What's Apnea?"
keywords:    "apnea, sleep, medical, diagnose, symptoms, referral, doctor"
description: "Your child might have sleep apnea and you've been referred to a specialist. In order to help your specialist make their evaluation, here’s what you’ll need to do."
source_link: "https://github.com/HackApnea/HackApnea.github.io"
favicon:     "img/favicon.ico"
touch_icon:  "img/apple-touch-icon.png"
google_analytics_key: UA-98289021-1


### template colors, used site-wide via css ###
colors:
  black:     '#111111'
  white:     '#f8f8f8'
  blue:      '#1976d2'
  bluetwo:   '#BBDEFB'
  green:     '#2e7d32'
  purple:    '#8e24aa'
  orange:    '#FFC107'
  turquoise: '#00838f'
  sbblue0: '#DAE8F5'
  sbblue1: '#BAD6EA'
  sbblue2: '#88BEDC'
  sbblue3: '#539DCC'
  sbblue4: '#2A7AB9'
  sbblue5: '#0B559F'

kramdown:
  auto_ids:  false

